### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by cyaccpect** [cv-rits/MonoScene#12]
PS F:\Studying\CY-Workspace\MonoScene-master>  python monoscene/scripts/train_monoscene.py dataset=kitti enable_log=true kitti_root=$KITTI_ROOT kitti_preprocess_root=$KITTI_PREPROCESS kit
ti_logdir=$KITTI_LOG n_gpus=1 batch_size= 1
LexerNoViableAltException: 1
                           ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by anhquancao** [comment]
Hi @cyaccpect
I think the error comes from the space between 
`batch_size= 1`

**Comment by cyaccpect** [comment]
thank you for your answer，I am beginner in this area. I have correted the error above ,but I get new question

PS F:\Studying\CY-Workspace\MonoScene-master>  python monoscene/scripts/train_monoscene.py dataset=kitti enable_log=true kitti_root=$KITTI_ROOT kitti_preprocess_root=$KITTI_PREPROCESS kit
ti_logdir=$KITTI_LOG n_gpus=1 batch_size=1
exp_kitti_1_FrusSize_8_nRelations4_WD0.0001_lr0.0001_CEssc_geoScalLoss_semScalLoss_fpLoss_CERel_3DCRP_Proj_2_4_8
n_relations 4
Using cache found in C:\Users\DELL/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
Traceback (most recent call last):
  File "monoscene/scripts/train_monoscene.py", line 184, in main
    trainer.fit(model, data_module)
  File "F:\anaconda\envs\monoscene\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 522, in fit
    self._run(model)
  File "F:\anaconda\envs\monoscene\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 829, in _run
    self.accelerator.setup_environment()
  File "F:\anaconda\envs\monoscene\lib\site-packages\pytorch_lightning\accelerators\gpu.py", line 30, in setup_environment
    super().setup_environment()
  File "F:\anaconda\envs\monoscene\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 81, in setup_environment
    self.training_type_plugin.setup_environment()
  File "F:\anaconda\envs\monoscene\lib\site-packages\pytorch_lightning\plugins\training_type\ddp.py", line 165, in setup_environment
    self.setup_distributed()
  File "F:\anaconda\envs\monoscene\lib\site-packages\pytorch_lightning\plugins\training_type\ddp.py", line 255, in setup_distributed
    self.init_ddp_connection()
  File "F:\anaconda\envs\monoscene\lib\site-packages\pytorch_lightning\plugins\training_type\ddp.py", line 324, in init_ddp_connection
    self.torch_distributed_backend, rank=global_rank, world_size=world_size
  File "F:\anaconda\envs\monoscene\lib\site-packages\torch\distributed\distributed_c10d.py", line 434, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "F:\anaconda\envs\monoscene\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by anhquancao** [comment]
I guess you are running on Window. I never try the code on Window.
However, I think the code will not work on Window BECAUSE we use "ddp" accelerator for multi-GPUs training, which is not supported on Window.
I suggest you run it on Linux e.g. Ubuntu

**Comment by cyaccpect** [comment]
you are right,I will try it on ubuntu again, very very very thank you！！Wish everything goes well with your work!

**Comment by anhquancao** [comment]
You too, thank you very much for your kind words! 
Good luck with your research!
